### ISSUE TITLE
Is the worker still needed?

### ISSUE THREAD

**Issue by lenvanessen** [jrrdnx/craft-cloudflare-r2#1]
Just seen this:
https://blog.cloudflare.com/r2-ga/

I believe it's not beta anymore, and also, public ACL's work!

**Comment by jrrdnx** [comment]
I saw that it was out of beta, but had not yet had a chance to look into this.

You can now enable public access directly from the Cloudflare dashboard, which is awesome! [https://developers.cloudflare.com/r2/data-access/public-buckets/#enable-public-access-for-your-bucket](https://developers.cloudflare.com/r2/data-access/public-buckets/#enable-public-access-for-your-bucket)

However, unless I'm missing something it appears to be all or nothing. So if you still need to limit access in a particular way (allow or deny specific directories, IP addresses/ranges, etc) then workers would still be the way to go. You can still add a custom domain to your worker just as you now can directly to your bucket so no change there.

**Comment by jrrdnx** [comment]
Released v1.0.0 with an updated README including links to Cloudflare docs on public access.
