### ISSUE TITLE
Support for bucket name environment variable

### ISSUE THREAD

**Issue by Thijmen** [jrrdnx/craft-cloudflare-r2#10]
Hi there,

First and foremost, thank you for this plugin. It works as a charm!

Currently, we have the account id, access key id and secret access key as an environment variable. This works fine for the same account, however when we're trying to develop and want to develop against a development bucket, it doesn't work because the bucket name changes (as expected). Is there a way to also have the bucket name as an environment variable, so we can easily change the environment without persisting/changing settings of a filesystem?

Thanks in advance,

Thijmen

**Comment by jrrdnx** [comment]
Thanks @Thijmen !

This is actually possible currently. For the Bucket field, choosing 'Manual' from the dropdown will allow you to enter a value, including environment variables, to specify the bucket name.

<img width="474" alt="Screenshot 2024-03-07 at 3 16 56 PM" src="https://github.com/jrrdnx/craft-cloudflare-r2/assets/4584671/dd1ccf41-d1ad-4920-9ee8-887d06561597">

**Comment by Thijmen** [comment]
That indeed does seems to work like a charm, totally missed this, thanks!
