### ISSUE TITLE
Secure Downloads

### ISSUE THREAD

**Issue by hheckel** [jrrdnx/craft-cloudflare-r2#8]
Can you make it work with https://github.com/kennethormandy/craft-s3securedownloads/?
Thanks.

**Comment by jrrdnx** [comment]
Have you tried this yet?

R2 implements the S3 API so this should theoretically already work. Looking at that plugin's source code it already seems to match R2's docs on how to generate presigned urls.

https://developers.cloudflare.com/r2/api/s3/presigned-urls
https://developers.cloudflare.com/r2/examples/aws/aws-sdk-php/#generate-presigned-urls

**Comment by thupsi** [comment]
Hi, just tried using this with [Secure S3 Downloads](https://github.com/kennethormandy/craft-s3securedownloads/) and I get this error when accessing the generated URL:  `Getting unknown property: jrrdnx\cloudflarer2\Fs::region`. 

Could you maybe look into this? Thanks!

**Comment by jrrdnx** [comment]
@thupsi R2 uses a value of `auto` for the bucket regions:

> When using the S3 API, the region for an R2 bucket is auto. For compatibility with tools that do not allow you to specify a region, an empty value and us-east-1 will alias to the auto region.

Regardless, I did some testing to see what it would take to get past this error and the generated URL is hard-coded to the `...s3.auto.amazonaws.com/...` domain so it wouldn't work without updates to the Secure S3 Downloads plugin.

**Comment by thupsi** [comment]
@jrrdnx Thanks for your insights! I will post an issue to the S3 Downloads repo then 🙂
